### ISSUE TITLE
Database Schema Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-vrzn#14]
- Remove tbl prefixes in your table names.
- Make your table names in singular format.
- Remove bank_id column in accounts table. All accounts in your account table belongs to your bank. You don't need to hold the information of accounts from another bank. You only need their bank code and account number.
- tbl_bank is optional, you will only refer it to get the details of other banks. If you want to save the details of other banks, then keep this table otherwise, you can omit it. The bank_code alone is a sufficient date and can be the primary key. no need for the bank_id.

Based on the columns, the tbl_transactions is for over-the-counter transactions performed by tellers. Then the tbl_transfer_funds holds both internal and external transfer. You did not distinguish bank teller and account holder and put them in a single table called users identified by user_type.

Please coordinate with Hypertechs team so you can compare your database schemas. Below are the tables that I intend in the design.  You can follow this schema or you can continue with your own if you are confident with your own design.

There are 3 live tables:
- bank_account which holds the current value of the balance
- bank_teller which holds the bank teller details
- account_holder which holds the account holder details

These tables are being updated frequently especially the bank_account table where you change the balance for every transaction. The table account_holder is one-to-many with bank_account because an account holder can have multiple bank accounts.

Then you have audit or history tables:
- over_the_counter_transactions
- internal_transfer_transactions
- external_transfer_transactions

These tables are not updated. In the real world, we do not store this in an SQL databases. We usually store it in a big data repository such as BigQuery and Hadoop. That's because these data are not updated. Once records are entered here, it will never be changed.

**Comment by go-christianharrel** [comment]
We appreciate your feedback, Sir. We'll incorporate these changes in our next sprint and make an effort to connect more with the Hypertechs. Currently, we have a GC for updates, and we're eager to collaborate with them moving forward. Thank you, Sir!

**Comment by go-christianharrel** [comment]
Good day, Sir. I've taken the initiative to link this issue to my pull request, ensuring automatic closure upon approval and merging by my assigned reviewers. Thank you for your valuable guidance!
