### ISSUE TITLE
Repository Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/project-vrzn#15]
- Remove unnecessary files in your repo such as sprint1_flowchart1.png. The reason why we use version control system is that we want to declutter our repository with different versions of files. If you need to view the changes in a file, do git diff or use UI based git plugins. What should remain in the repo are only the updated single version of a file.
- If you want to store your project management details in the repository, that's fine but organize it and keep in a single folder say "project management" or the like.

**Comment by go-christianharrel** [comment]
Noted, Sir. Thank you for your guidance!

**Comment by go-christianharrel** [comment]
Good day, Sir. I've taken the initiative to link this issue to my pull request, ensuring automatic closure upon approval and merging by my assigned reviewers. Thank you for your valuable guidance!
